// AUTO-GENERATED by build_executor.mjs
// Tool executor — imports the schema from tools-schema.js.

import { TOOLS } from './tools-schema.js';
import { S, saveState, recordEdit } from './state.js';
import { Bus, toast, uid } from './utils.js';
import { ICONS } from './icons.js';
import { fsRead, fsWrite, fsList, fsMkdir, fsDelete, fsRename,
         fsReadRange, initIDBSession, switchWorkspace,
         deleteSession, refreshSessions, machOpen } from './fs.js';
import { diffLines } from './diff.js';
import { apiChat, streamChatWithRetry } from './api.js';
import { spawnSubagent } from './subagents.js';
import { createArtifact } from './artifacts.js';
import { recordPendingDiff } from './review.js';
import { makeClarifyWidget, makeSQWidget } from './widgets.js';

export { TOOLS };

// Pending user-input resolvers (approval widgets, clarify, simple_question).
// When the agent run is aborted (stop button), these are resolved/rejected
// so the run-loop doesn't hang forever on a widget nobody can answer.
const pendingResolvers = new Set();
Bus.on('agent:abort', () => {
  for (const fn of pendingResolvers) {
    try { fn(); } catch {}
  }
  pendingResolvers.clear();
});

/**
 * In edit mode, show diff and wait for user approval.
 * Uses the same .diff-blk styling as the inline diff renderer in ui.js,
 * with Accept/Reject controls appended below the diff body.
 * Returns a Promise that resolves to true (approved) or false (rejected).
 */
function waitForApproval(path, diff, isNew) {
  return new Promise((resolve) => {
    const settle = (val) => {
      pendingResolvers.delete(abortHandler);
      resolve(val);
    };
    const abortHandler = () => {
      blk.querySelectorAll('button').forEach(b => b.disabled = true);
      blk.style.opacity = '.4';
      settle(false);
    };
    pendingResolvers.add(abortHandler);

    const blk = document.createElement('div');
    blk.className = 'diff-blk approval-widget';

    const fname = path.split('/').pop();
    const hd = document.createElement('div');
    hd.className = 'diff-hd';

    const left = document.createElement('span');
    left.className = 'diff-fn';
    left.textContent = (isNew ? 'Create: ' : 'Edit: ') + fname;

    const right = document.createElement('span');
    right.className = 'diff-st';
    if (isNew) {
      const nb = document.createElement('span');
      nb.style.color = 'var(--teal)';
      nb.textContent = 'new ';
      right.appendChild(nb);
    }
    const add = document.createElement('span');
    add.className = 'diff-add-c';
    add.textContent = '+' + diff.stats.add + ' ';
    const del = document.createElement('span');
    del.className = 'diff-del-c';
    del.textContent = '-' + diff.stats.del;
    right.append(add, del);

    hd.append(left, right);

    const body = document.createElement('div');
    body.style.cssText = 'padding:3px 0;max-height:240px;overflow-y:auto;';
    for (const line of diff.lines) {
      const el = document.createElement('div');
      if (line.t === 'gap') {
        el.className = 'diff-line gap';
        el.innerHTML = '<span class="diff-pfx">\u2026</span><span style="color:var(--txt3);font-style:italic">unchanged</span>';
      } else {
        const cls = { add: 'add', del: 'del', ctx: 'ctx' }[line.t] || 'ctx';
        const pfx = { add: '+', del: '-', ctx: ' ' }[line.t] || ' ';
        el.className = 'diff-line ' + cls;
        const pfxSpan = document.createElement('span');
        pfxSpan.className = 'diff-pfx';
        pfxSpan.textContent = pfx;
        el.appendChild(pfxSpan);
        el.appendChild(document.createTextNode(line.s || ''));
      }
      body.appendChild(el);
    }

    const actions = document.createElement('div');
    actions.style.cssText = 'display:flex;gap:6px;justify-content:flex-end;padding:8px 10px;border-top:1px solid var(--border);';

    const rejectBtn = document.createElement('button');
    rejectBtn.className = 'btn sm';
    rejectBtn.textContent = 'Reject';
    rejectBtn.style.borderColor = 'rgba(245,83,79,.4)';
    rejectBtn.style.color = 'var(--red)';
    rejectBtn.onclick = () => {
      actions.querySelectorAll('button').forEach(b => b.disabled = true);
      blk.style.opacity = '.55';
      settle(false);
    };

    const acceptBtn = document.createElement('button');
    acceptBtn.className = 'btn sm prim';
    acceptBtn.textContent = 'Accept';
    acceptBtn.onclick = () => {
      actions.querySelectorAll('button').forEach(b => b.disabled = true);
      blk.style.opacity = '.55';
      settle(true);
    };

    actions.append(rejectBtn, acceptBtn);
    blk.append(hd, body, actions);

    // Append to the current agent turn (where tool outputs live)
    const turn = document.querySelector('.msg-agent:last-child')
              || document.getElementById('msgs')
              || document.body;
    turn.appendChild(blk);
    blk.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  });
}

export async function execTool(name, args) {
  switch (name) {

    case 'suggest_mode': {
      // In YOLO, apply immediately without blocking — the agent is
      // operating autonomously and shouldn't stall on its own suggestion.
      if (S.mode === 'yolo') {
        return { success: true, _ui: 'suggest_mode', mode: args.mode, reason: args.reason, blocking: false,
          message: `Suggested: ${args.mode} — ${args.reason}` };
      }
      // In PLAN/EDIT, block until the user accepts or skips. This prevents
      // the agent from assuming a mode switch happened when it didn't —
      // it must wait for the actual outcome before continuing.
      return new Promise(resolve => {
        const settle = (val) => { pendingResolvers.delete(abortHandler); resolve(val); };
        const abortHandler = () => settle({ success: false, message: 'Cancelled by user.', cancelled: true, _ui: 'suggest_mode', mode: args.mode, reason: args.reason, resolved: 'cancelled' });
        pendingResolvers.add(abortHandler);
        Bus.emit('widget:suggest_mode', { mode: args.mode, reason: args.reason, settle });
      });
    }

    case 'init_filesystem': {
      if (args.type === 'machine') {
        const n = await machOpen();
        if (n) { Bus.emit('fs:init', { type: 'machine', name: n }); return { success: true, message: 'Opened folder: ' + n }; }
        return { success: false, message: 'User cancelled folder picker.' };
      }
      const sn = await initIDBSession({ name: args.name, firstPrompt: args.firstPrompt });
      return { success: true, message: 'IDB session ready: ' + sn, session: sn };
    }

    case 'switch_workspace': {
      const sn = await switchWorkspace(args.name);
      return { success: true, message: 'Switched to session: ' + sn, session: sn };
    }

    case 'list_workspaces': {
      const list = await refreshSessions();
      const text = list.length
        ? list.map(s => `${s.active ? '→' : ' '} ${s.name}  (${s.size} files)  — ${s.displayName}${s.firstPrompt ? ' :: ' + s.firstPrompt.slice(0, 50) : ''}`).join('\n')
        : '(no sessions yet)';
      return { success: true, sessions: list, message: text };
    }

    case 'delete_workspace':
      await deleteSession(args.name);
      return { success: true, message: 'Deleted session: ' + args.name };

    case 'save_to_memory': {
      const i = S.memory.findIndex(m => m.key === args.key);
      const entry = { key: args.key, val: args.value, ts: Date.now() };
      if (i >= 0) S.memory[i] = entry; else S.memory.push(entry);
      saveState();
      Bus.emit('memory:update', S.memory);
      return { success: true, message: `Memory saved: "${args.key}"` };
    }

    case 'list_directory': {
      const items = await fsList(args.path);
      const text = items.map(i => (i.type === 'dir' ? '[DIR] ' : '[FILE] ') + i.name).join('\n');
      return { success: true, items, message: text || '(empty)' };
    }

    case 'read_file': {
      const content = await fsRead(args.path);
      return { success: true, content, path: args.path, lines: content.split('\n').length };
    }

    case 'read_file_range': {
      const r = await fsReadRange(args.path, args.offset || 0, args.limit || 100);
      return {
        success: true, content: r.content, path: args.path,
        offset: r.offset, total: r.total,
        message: `Lines ${r.offset + 1}-${Math.min(r.offset + r.limit, r.total)} of ${r.total}`,
      };
    }

    case 'read_many_files': {
      const results = {}, errors = {};
      for (const p of args.paths) {
        try { results[p] = await fsRead(p); } catch (e) { errors[p] = e.message; }
      }
      return { success: true, results, errors };
    }

    case 'write_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: writes not allowed.' };
      let before = '';
      try { before = await fsRead(args.path); } catch {}
      const diff = diffLines(before, args.content);
      const isNew = !before;
      
      // In edit mode, wait for user approval before applying
      if (S.mode === 'edit') {
        const approved = await waitForApproval(args.path, diff, isNew);
        if (!approved) {
          return { success: false, message: `User rejected changes to ${args.path}` };
        }
      }
      
      await fsWrite(args.path, args.content);
      Bus.emit('fs:changed', { path: args.path });
      // Only queue for batch review in YOLO mode (edit mode already approved inline)
      if (S.mode === 'yolo') {
        recordPendingDiff({ path: args.path, before, after: args.content, diff, isNew });
      }
      recordEdit(args.path, before, args.content, 'write_file', args);
      return { success: true, path: args.path, diff, isNew, _ui: 'diff',
        message: (before ? 'Wrote ' : 'Created ') + args.path + ` (+${diff.stats.add}, -${diff.stats.del})` };
    }

    case 'edit_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: edits not allowed.' };
      let content = '', isNew = false;
      try { content = await fsRead(args.path); }
      catch (e) {
        if (args.create_if_missing) { content = ''; isNew = true; } else throw e;
      }
      let next = isNew ? (args.full_content || '') : content;
      const failed = [];
      if (!isNew && args.changes) {
        for (const c of args.changes) {
          if (next.includes(c.old)) next = next.replace(c.old, c.new);
          else failed.push('"' + c.old.slice(0, 40) + (c.old.length > 40 ? '...' : '') + '"');
        }
      } else if (args.full_content !== undefined) {
        next = args.full_content;
      }
      if (failed.length) return { success: false, message: `Could not find ${failed.length} change(s). Read the file again: ${failed.join(', ')}` };
      
      const diff = diffLines(isNew ? '' : content, next);
      
      // In edit mode, wait for user approval before applying
      if (S.mode === 'edit') {
        const approved = await waitForApproval(args.path, diff, isNew);
        if (!approved) {
          return { success: false, message: `User rejected changes to ${args.path}` };
        }
      }
      
      await fsWrite(args.path, next);
      Bus.emit('fs:changed', { path: args.path });
      // Only queue for batch review in YOLO mode (edit mode already approved inline)
      if (S.mode === 'yolo') {
        recordPendingDiff({ path: args.path, before: content, after: next, diff, isNew });
      }
      recordEdit(args.path, content, next, 'edit_file', args);
      return { success: true, path: args.path, diff, isNew, _ui: 'diff',
        message: (isNew ? 'Created ' : 'Edited ') + args.path + ` (+${diff.stats.add}, -${diff.stats.del})` };
    }

    case 'delete_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: deletes not allowed.' };
      await fsDelete(args.path);
      Bus.emit('fs:changed', { path: args.path });
      return { success: true, message: 'Deleted: ' + args.path };
    }

    case 'rename_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: renames not allowed.' };
      await fsRename(args.old_path, args.new_path);
      Bus.emit('fs:changed', { path: args.new_path });
      return { success: true, message: `Renamed: ${args.old_path} → ${args.new_path}` };
    }

    case 'make_directory': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: mkdir not allowed.' };
      await fsMkdir(args.path);
      Bus.emit('fs:changed', { path: args.path });
      return { success: true, message: 'Created directory: ' + args.path };
    }

    case 'web_search': {
      try {
        const max = args.max_results || 8;
        const resp = await fetch(`/v1/search?q=${encodeURIComponent(args.query)}&max=${max}`);
        if (!resp.ok) {
          const err = await resp.json().catch(() => ({}));
          return { success: false, message: err.detail || `Search failed: HTTP ${resp.status}` };
        }
        const data = await resp.json();
        const results = data.results || [];
        const formatted = results.map((r, i) =>
          `${i + 1}. **${r.title}**\n   ${r.url}\n   ${r.snippet}`
        ).join('\n\n');
        return {
          success: true,
          results,
          _ui: 'search',
          message: results.length
            ? `Found ${results.length} results for "${args.query}":\n\n${formatted}`
            : `No results found for "${args.query}"`,
        };
      } catch (e) {
        return { success: false, message: 'Search error: ' + e.message };
      }
    }

    case 'extract_from_url': {
      try {
        const max = args.max_chars || 12000;
        const resp = await fetch(`/v1/extract?url=${encodeURIComponent(args.url)}&max_chars=${max}`);
        if (!resp.ok) {
          const err = await resp.json().catch(() => ({}));
          return { success: false, message: err.detail || `Extract failed: HTTP ${resp.status}` };
        }
        const data = await resp.json();
        return {
          success: true,
          text: data.text,
          chars: data.chars,
          url: args.url,
          message: data.text,
        };
      } catch (e) {
        return { success: false, message: 'Extract error: ' + e.message };
      }
    }

    case 'search_in_files': {
      if (!S.fsMode) return { success: false, message: 'No workspace open.' };
      const maxResults = args.max_results || 50;
      const caseSensitive = args.case_sensitive || false;
      let rx;
      try {
        rx = new RegExp(args.pattern, caseSensitive ? 'g' : 'gi');
      } catch {
        // If the pattern isn't valid regex, treat it as a literal string.
        rx = new RegExp(args.pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), caseSensitive ? 'g' : 'gi');
      }

      const matches = [];
      const searchDir = args.path || S.cwd;
      const fileGlob = (args.file_glob || '').toLowerCase();

      // Recursive file walker using fsList.
      const walk = async (dir) => {
        if (matches.length >= maxResults) return;
        let items;
        try { items = await fsList(dir); } catch { return; }
        for (const it of items) {
          if (matches.length >= maxResults) break;
          const fullPath = S.fsMode === 'idb' ? dir + it.name : it.path || (dir.replace(/\/$/, '') + '/' + it.name);
          if (it.type === 'dir') {
            if (it.name === 'node_modules' || it.name === '.git') continue;
            await walk(fullPath + '/');
          } else {
            if (fileGlob && !it.name.toLowerCase().includes(fileGlob)) continue;
            try {
              const content = await fsRead(fullPath);
              const lines = content.split('\n');
              lines.forEach((line, i) => {
                if (matches.length >= maxResults) return;
                if (rx.test(line)) {
                  rx.lastIndex = 0; // reset stateful regex
                  matches.push({ file: fullPath, line: i + 1, text: line.trim().slice(0, 200) });
                }
                rx.lastIndex = 0;
              });
            } catch { /* unreadable — skip */ }
          }
        }
      };

      await walk(searchDir.endsWith('/') ? searchDir : searchDir + '/');

      if (!matches.length) {
        return { success: true, matches: [], message: `No matches for "${args.pattern}"` };
      }
      const formatted = matches.map(m => `${m.file}:${m.line}  ${m.text}`).join('\n');
      return { success: true, matches, truncated: matches.length >= maxResults,
        message: `${matches.length}${matches.length >= maxResults ? '+' : ''} match${matches.length === 1 ? '' : 'es'} for "${args.pattern}":\n\n${formatted}` };
    }

    case 'git_status': {
      if (S.fsMode !== 'machine') return { success: false, message: 'Git only in machine mode.' };
      const { machGit } = await import('./fs.js');
      const br = await machGit();
      S.gitBranch = br;
      Bus.emit('status:update', {});
      return { success: true, branch: br, message: br ? 'Branch: ' + br : 'Not a git repo.' };
    }

    case 'fetch_request': {
      try {
        const opts = { method: args.method || 'GET', headers: args.headers || {} };
        if (args.body) opts.body = args.body;
        const r = await fetch(args.url, opts);
        const text = (await r.text()).slice(0, 8000);
        return { success: true, status: r.status, body: text, _ui: 'fetch' };
      } catch (e) { return { success: false, message: 'Fetch error: ' + e.message }; }
    }

    case 'add_todo': {
      S.todos.push({ text: args.text, list: args.list || 'main', done: false, id: uid(), ts: Date.now() });
      saveState();
      Bus.emit('todos:update', S.todos);
      return { success: true, message: 'TODO added: "' + args.text + '"' };
    }

    case 'complete_todo': {
      const list = args.list || 'main';
      const filtered = S.todos.filter(t => t.list === list);
      if (args.index >= 0 && args.index < filtered.length) {
        filtered[args.index].done = true;
        saveState();
        Bus.emit('todos:update', S.todos);
        return { success: true, message: 'Completed: "' + filtered[args.index].text + '"' };
      }
      return { success: false, message: 'Index ' + args.index + ' not found' };
    }

    case 'list_todos': {
      const t = args.list ? S.todos.filter(x => x.list === args.list) : S.todos;
      return { success: true, todos: t,
        message: t.length ? t.map((x, i) => (x.done ? '✓' : '○') + ` [${i}] ${x.text}`).join('\n') : 'No todos' };
    }

    case 'display_markdown':
      return { success: true, _ui: 'markdown', content: args.content, title: args.title };

    case 'run_javascript': {
      // Run inside a sandboxed iframe so the code can't access S, Bus,
      // localStorage, DOM, or any other page globals. Results come back
      // via postMessage.
      return new Promise(resolve => {
        const iframe = document.createElement('iframe');
        iframe.sandbox = 'allow-scripts';
        iframe.style.display = 'none';
        document.body.appendChild(iframe);

        const logs = [];
        const tid = uid();
        let settled = false;

        const cleanup = () => {
          window.removeEventListener('message', handler);
          iframe.remove();
        };
        const settle = (out, err) => {
          if (settled) return;
          settled = true;
          cleanup();
          clearTimeout(timer);
          resolve({ success: !err, output: out, error: err, _ui: 'js',
            message: err ? 'Error: ' + err : (out || '(no output)') });
        };

        // 5s timeout — prevents infinite loops from hanging the agent.
        const timer = setTimeout(() => settle('', 'Execution timed out (5s)'), 5000);

        const handler = (e) => {
          if (!e.data || e.data._ariaId !== tid) return;
          settle(e.data.output || '', e.data.error || '');
        };
        window.addEventListener('message', handler);

        const src = `
          <script>
          const _logs = [];
          const _con = { log: (...a) => _logs.push(a.map(x => typeof x === 'object' ? JSON.stringify(x, null, 2) : String(x)).join(' ')),
                         error: (...a) => _logs.push('[err] ' + a.join(' ')),
                         warn: (...a) => _logs.push('[warn] ' + a.join(' ')) };
          try {
            (function(console) {
              "use strict";
              ${args.code.replace(/<\/script>/gi, '<\\/script>')}
            })(_con);
            parent.postMessage({ _ariaId: ${JSON.stringify(tid)}, output: _logs.join('\\n'), error: '' }, '*');
          } catch(e) {
            parent.postMessage({ _ariaId: ${JSON.stringify(tid)}, output: _logs.join('\\n'), error: e.message }, '*');
          }
          <\/script>`;
        iframe.srcdoc = src;
      });
    }

    case 'display_html':
      return { success: true, _ui: 'html', html: args.html, title: args.title, height: args.height || 300 };

    case 'create_artifact': {
      const art = await createArtifact(args);
      return { success: true, _ui: 'artifact', artifact: art,
        message: `Artifact created: ${args.title} (${args.type})` };
    }

    case 'spawn_subagent': {
      const result = await spawnSubagent(args.task, args.system_prompt);
      return { success: true, summary: result.summary, _ui: 'subagent',
        message: 'Subagent completed: ' + result.summary.slice(0, 200) };
    }

    case 'search_conversations': {
      const q = args.query.toLowerCase();
      // Strip base64 image data from messages before stringifying for search —
      // it's huge, never matches text queries, and chokes the string ops.
      const searchable = (msgs) => JSON.stringify(msgs.map(m => {
        if (!Array.isArray(m.content)) return m;
        return { ...m, content: m.content.map(b => b.type === 'image_url' ? { type: 'image_url', image_url: '[image]' } : b) };
      }));
      const r = S.convs.filter(c => (c.title + searchable(c.msgs || [])).toLowerCase().includes(q)).slice(0, 5);
      return { success: true, results: r,
        message: r.length ? r.map(c => `"${c.title}"`).join(', ') : 'No matches.' };
    }

    case 'date_now': {
      const n = new Date();
      return { success: true, iso: n.toISOString(), local: n.toLocaleString(),
        message: n.toLocaleString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }) };
    }

    case 'make_pdf': {
      const w = window.open('', '_blank');
      w.document.write(`<!DOCTYPE html><html><head><title>${args.filename || 'doc'}</title>
<style>body{font-family:Georgia,serif;max-width:780px;margin:48px auto;padding:20px;font-size:14px;line-height:1.7;}
h1,h2,h3{font-family:sans-serif;}code{background:#f4f4f4;padding:2px 5px;border-radius:3px;font-size:12px;}
pre{background:#f4f4f4;padding:10px;border-radius:5px;overflow:auto;}</style>
</head><body><pre id=c></pre><script>
const raw=document.getElementById('c');
raw.style.whiteSpace='pre-wrap';raw.style.fontFamily='Georgia,serif';raw.style.background='none';raw.style.padding='0';
raw.textContent=${JSON.stringify(args.content)};window.print();<\/script></body></html>`);
      w.document.close();
      return { success: true, message: 'PDF print dialog opened for: ' + (args.filename || 'document') };
    }

    case 'clarify': {
      return new Promise(resolve => {
        const settle = (val) => { pendingResolvers.delete(abortHandler); resolve(val); };
        const abortHandler = () => settle({ success: false, message: 'Cancelled by user.', cancelled: true });
        pendingResolvers.add(abortHandler);
        const w = makeClarifyWidget(args.question, ans => settle({ success: true, answer: ans }));
        Bus.emit('widget:append', w);
        if (S.mode === 'yolo') {
          setTimeout(() => {
            const def = args.default_answer || 'Continue with best default.';
            const input = w.querySelector('.clr-inp');
            if (input) { input.value = def; input.disabled = true; }
            settle({ success: true, answer: def, auto: true });
          }, 30000);
        }
      });
    }

    case 'simple_question': {
      return new Promise(resolve => {
        const settle = (val) => { pendingResolvers.delete(abortHandler); resolve(val); };
        const abortHandler = () => settle({ success: false, message: 'Cancelled by user.', cancelled: true });
        pendingResolvers.add(abortHandler);
        const w = makeSQWidget(args.question, args.options, ans => settle({ success: true, answer: ans }));
        Bus.emit('widget:append', w);
        if (S.mode === 'yolo') {
          const di = Math.max(0, Math.min((args.default_index ?? 0), (args.options?.length ?? 1) - 1));
          setTimeout(() => settle({ success: true, answer: args.options[di], auto: true }), 30000);
        }
      });
    }

    case 'think_deeper': {
      // Emit start event so UI can create a dedicated block for streaming
      Bus.emit('turn:think_deeper_start', args.problem);

      const sys = {
        role: 'user',
        content: `Think deeply about this problem and provide thorough analysis:\n\n**Problem:** ${args.problem}${args.context ? '\n\n**Context:** ' + args.context : ''}\n\nProvide clear analysis and concrete next steps.`
      };

      let accumulated = '';
      const resp = await streamChatWithRetry([sys], null, {
        onDelta(chunk, full) {
          accumulated = full;
          Bus.emit('turn:think_deeper_delta', full);
        }
      });

      const analysis = resp?.content || accumulated || 'No analysis generated';
      return { success: true, analysis, _ui: 'think_deeper' };
    }

    default:
      return { success: false, message: 'Unknown tool: ' + name };
  }
}
