// AUTO-GENERATED by build_tools.mjs on 2026-06-01T16:01:25.662Z
// Tool schema for Mistral function-calling.

export const TOOLS = [
  {
    "type": "function",
    "function": {
      "name": "suggest_mode",
      "description": "Suggest the user switch mode or open a workspace. Renders a clickable action.",
      "parameters": {
        "type": "object",
        "properties": {
          "mode": {
            "type": "string",
            "description": "Target mode",
            "enum": [
              "plan",
              "edit",
              "yolo",
              "open_folder",
              "new_idb"
            ]
          },
          "reason": {
            "type": "string",
            "description": "Why this mode is appropriate"
          }
        },
        "required": [
          "mode",
          "reason"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "init_filesystem",
      "description": "Initialize a workspace. type=idb with optional name/firstPrompt, or type=machine (triggers picker).",
      "parameters": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "Workspace type",
            "enum": [
              "idb",
              "machine"
            ]
          },
          "name": {
            "type": "string",
            "description": "Optional session name"
          },
          "firstPrompt": {
            "type": "string",
            "description": "Stamped as firstPrompt metadata"
          }
        },
        "required": [
          "type"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "switch_workspace",
      "description": "Switch to an existing IDB session. Use list_workspaces first.",
      "parameters": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Session name to switch to"
          }
        },
        "required": [
          "name"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "list_workspaces",
      "description": "List all known IDB sessions.",
      "parameters": {
        "type": "object",
        "properties": {}
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "delete_workspace",
      "description": "Permanently delete an IDB session.",
      "parameters": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Session name to delete"
          }
        },
        "required": [
          "name"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "save_to_memory",
      "description": "Save a note to persistent memory across conversations.",
      "parameters": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "description": "Memory key"
          },
          "value": {
            "type": "string",
            "description": "Memory value"
          }
        },
        "required": [
          "key",
          "value"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "list_directory",
      "description": "List directory contents.",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "Directory path"
          }
        },
        "required": [
          "path"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "read_file",
      "description": "Read a file. For >500 lines, prefer read_file_range.",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "File path"
          }
        },
        "required": [
          "path"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "read_file_range",
      "description": "Read a slice of a file (offset + limit lines).",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "File path"
          },
          "offset": {
            "type": "number",
            "description": "Starting line (0-indexed)"
          },
          "limit": {
            "type": "number",
            "description": "Number of lines to read"
          }
        },
        "required": [
          "path",
          "offset",
          "limit"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "read_many_files",
      "description": "Read multiple files in one call. Errors are returned per-file.",
      "parameters": {
        "type": "object",
        "properties": {
          "paths": {
            "type": "array",
            "description": "Array of file paths",
            "items": {
              "type": "string",
              "description": "File path"
            }
          }
        },
        "required": [
          "paths"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "write_file",
      "description": "Write a complete file (overwrites if exists).",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "File path"
          },
          "content": {
            "type": "string",
            "description": "Full file content"
          }
        },
        "required": [
          "path",
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "edit_file",
      "description": "Edit a file by replacing specific text blocks.",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "File path"
          },
          "changes": {
            "type": "array",
            "description": "Array of {old, new} replacements",
            "items": {
              "type": "object",
              "properties": {
                "old": {
                  "type": "string",
                  "description": "Text to replace"
                },
                "new": {
                  "type": "string",
                  "description": "Replacement text"
                }
              },
              "required": [
                "old",
                "new"
              ]
            }
          },
          "create_if_missing": {
            "type": "boolean",
            "description": "Create the file if it does not exist"
          },
          "full_content": {
            "type": "string",
            "description": "Full content (used when creating)"
          }
        },
        "required": [
          "path"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "delete_file",
      "description": "Delete a file. Throws in machine mode.",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "File path to delete"
          }
        },
        "required": [
          "path"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "rename_file",
      "description": "Rename/move a file (IDB only).",
      "parameters": {
        "type": "object",
        "properties": {
          "old_path": {
            "type": "string",
            "description": "Current path"
          },
          "new_path": {
            "type": "string",
            "description": "New path"
          }
        },
        "required": [
          "old_path",
          "new_path"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "make_directory",
      "description": "Create a directory (mkdir -p).",
      "parameters": {
        "type": "object",
        "properties": {
          "path": {
            "type": "string",
            "description": "Directory path"
          }
        },
        "required": [
          "path"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "think_deeper",
      "description": "Reason through a complex problem thoroughly before proceeding.",
      "parameters": {
        "type": "object",
        "properties": {
          "problem": {
            "type": "string",
            "description": "The problem to think about"
          },
          "context": {
            "type": "string",
            "description": "Optional context"
          }
        },
        "required": [
          "problem"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "clarify",
      "description": "Ask the user a free-form question and wait for their response.",
      "parameters": {
        "type": "object",
        "properties": {
          "question": {
            "type": "string",
            "description": "The question"
          },
          "default_answer": {
            "type": "string",
            "description": "Default in YOLO mode if user does not respond"
          }
        },
        "required": [
          "question"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "simple_question",
      "description": "Ask the user a multiple-choice question.",
      "parameters": {
        "type": "object",
        "properties": {
          "question": {
            "type": "string",
            "description": "The question"
          },
          "options": {
            "type": "array",
            "description": "Choices",
            "items": {
              "type": "string",
              "description": "Option text"
            }
          },
          "default_index": {
            "type": "number",
            "description": "Default choice index in YOLO mode"
          }
        },
        "required": [
          "question",
          "options"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "fetch_request",
      "description": "Make an HTTP request.",
      "parameters": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "description": "URL to fetch"
          },
          "method": {
            "type": "string",
            "description": "HTTP method",
            "enum": [
              "GET",
              "POST",
              "PUT",
              "DELETE",
              "PATCH"
            ]
          },
          "headers": {
            "type": "object",
            "description": "Optional headers"
          },
          "body": {
            "type": "string",
            "description": "Optional body"
          }
        },
        "required": [
          "url"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "add_todo",
      "description": "Add a TODO item to a named list (default: main).",
      "parameters": {
        "type": "object",
        "properties": {
          "text": {
            "type": "string",
            "description": "TODO text"
          },
          "list": {
            "type": "string",
            "description": "List name"
          }
        },
        "required": [
          "text"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "complete_todo",
      "description": "Mark a TODO as done.",
      "parameters": {
        "type": "object",
        "properties": {
          "index": {
            "type": "number",
            "description": "Index of the TODO in its list"
          },
          "list": {
            "type": "string",
            "description": "List name"
          }
        },
        "required": [
          "index"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "list_todos",
      "description": "List TODOs, optionally filtered to one list.",
      "parameters": {
        "type": "object",
        "properties": {
          "list": {
            "type": "string",
            "description": "Optional list name filter"
          }
        }
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "display_markdown",
      "description": "Render a markdown block in the chat.",
      "parameters": {
        "type": "object",
        "properties": {
          "content": {
            "type": "string",
            "description": "Markdown content"
          },
          "title": {
            "type": "string",
            "description": "Optional title"
          }
        },
        "required": [
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "run_javascript",
      "description": "Execute a JS snippet in a sandbox. Use console.log for output.",
      "parameters": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": "JavaScript code"
          }
        },
        "required": [
          "code"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "display_html",
      "description": "Render HTML in a sandboxed iframe.",
      "parameters": {
        "type": "object",
        "properties": {
          "html": {
            "type": "string",
            "description": "HTML content"
          },
          "title": {
            "type": "string",
            "description": "Optional title"
          },
          "height": {
            "type": "number",
            "description": "Height in pixels"
          }
        },
        "required": [
          "html"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "create_artifact",
      "description": "Create a persistent artifact (HTML, code, markdown, SVG).",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Artifact title"
          },
          "type": {
            "type": "string",
            "description": "Type",
            "enum": [
              "html",
              "code",
              "markdown",
              "svg"
            ]
          },
          "language": {
            "type": "string",
            "description": "Code language"
          },
          "content": {
            "type": "string",
            "description": "Content"
          }
        },
        "required": [
          "title",
          "type",
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "spawn_subagent",
      "description": "Delegate a self-contained task to a subagent. Returns a structured summary.",
      "parameters": {
        "type": "object",
        "properties": {
          "task": {
            "type": "string",
            "description": "Task description"
          },
          "system_prompt": {
            "type": "string",
            "description": "Optional custom system prompt"
          }
        },
        "required": [
          "task"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "search_conversations",
      "description": "Search past conversations.",
      "parameters": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "Search query"
          }
        },
        "required": [
          "query"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "date_now",
      "description": "Get current date and time.",
      "parameters": {
        "type": "object",
        "properties": {}
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "make_pdf",
      "description": "Open browser print dialog to save content as PDF.",
      "parameters": {
        "type": "object",
        "properties": {
          "content": {
            "type": "string",
            "description": "Text content"
          },
          "filename": {
            "type": "string",
            "description": "Document filename"
          }
        },
        "required": [
          "content"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "web_search",
      "description": "Search the web via the local server proxy (DuckDuckGo, no API key needed). Returns titles, URLs, and snippets. Use for research, current events, documentation lookup, or anything requiring up-to-date information. Chain with extract_from_url to read full content.",
      "parameters": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "Search query"
          },
          "max_results": {
            "type": "number",
            "description": "Max results to return (default 8, max 20)"
          }
        },
        "required": ["query"]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "extract_from_url",
      "description": "Fetch a URL and extract clean readable text, stripping navigation, ads, and scripts. Use after web_search to read the full content of a promising result. Also works on documentation pages, articles, and GitHub READMEs.",
      "parameters": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "description": "URL to fetch and extract text from"
          },
          "max_chars": {
            "type": "number",
            "description": "Max characters to return (default 12000)"
          }
        },
        "required": ["url"]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "search_in_files",
      "description": "Search for a pattern (string or regex) across files in the workspace. Returns matching lines with file path and line number. Use instead of reading every file one-by-one when looking for usages, definitions, or strings.",
      "parameters": {
        "type": "object",
        "properties": {
          "pattern": {
            "type": "string",
            "description": "Search string or JavaScript regex pattern (e.g. 'myFunction' or 'function\\s+myFunc')"
          },
          "path": {
            "type": "string",
            "description": "Directory to search (default: workspace root). Use '.' for root."
          },
          "file_glob": {
            "type": "string",
            "description": "Optional file extension filter, e.g. '.js' or '.py'. Matches any file whose name includes this string."
          },
          "max_results": {
            "type": "number",
            "description": "Max matching lines to return (default 50)"
          },
          "case_sensitive": {
            "type": "boolean",
            "description": "Case-sensitive search (default false)"
          }
        },
        "required": ["pattern"]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "git_status",
      "description": "Get git branch (machine mode only).",
      "parameters": {
        "type": "object",
        "properties": {}
      }
    }
  }
];
