// AUTO-GENERATED by build_executor.mjs
// Tool executor — imports the schema from tools-schema.js.

import { TOOLS } from './tools-schema.js';
import { S, saveState, recordEdit } from './state.js';
import { Bus, toast, uid } from './utils.js';
import { ICONS } from './icons.js';
import { fsRead, fsWrite, fsList, fsMkdir, fsDelete, fsRename,
         fsReadRange, initIDBSession, switchWorkspace,
         deleteSession, refreshSessions, machOpen } from './fs.js';
import { diffLines } from './diff.js';
import { apiChat } from './api.js';
import { spawnSubagent } from './subagents.js';
import { createArtifact } from './artifacts.js';
import { recordPendingDiff } from './review.js';
import { makeClarifyWidget, makeSQWidget } from './widgets.js';

export { TOOLS };

/**
 * In edit mode, show diff and wait for user approval.
 * Returns a Promise that resolves to true (approved) or false (rejected).
 */
function waitForApproval(path, diff, isNew) {
  return new Promise((resolve) => {
    const widget = document.createElement('div');
    widget.className = 'approval-widget';
    widget.style.cssText = 'background:#1e1e1e;border:2px solid #4a4a4a;border-radius:8px;padding:12px;margin:8px 0;';
    
    const header = document.createElement('div');
    header.style.cssText = 'display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;';
    
    const title = document.createElement('div');
    title.style.cssText = 'color:#00ff00;font-weight:bold;font-size:14px;';
    title.textContent = `${isNew ? 'Create' : 'Edit'}: ${path}`;
    
    const stats = document.createElement('div');
    stats.style.cssText = 'color:#888;font-size:12px;';
    stats.textContent = `+${diff.stats.add} -${diff.stats.del}`;
    
    header.append(title, stats);
    
    const diffView = document.createElement('div');
    diffView.style.cssText = 'background:#0d0d0d;border:1px solid #333;border-radius:4px;padding:8px;max-height:200px;overflow-y:auto;font-family:monospace;font-size:11px;line-height:1.4;margin-bottom:12px;';
    
    // Render diff lines
    for (const line of diff.lines) {
      const lineEl = document.createElement('div');
      if (line.t === 'add') {
        lineEl.style.color = '#2ea043';
        lineEl.textContent = '+ ' + line.s;
      } else if (line.t === 'del') {
        lineEl.style.color = '#f85149';
        lineEl.textContent = '- ' + line.s;
      } else if (line.t === 'ctx') {
        lineEl.style.color = '#888';
        lineEl.textContent = '  ' + line.s;
      } else {
        lineEl.style.color = '#666';
        lineEl.textContent = '...';
      }
      diffView.appendChild(lineEl);
    }
    
    const buttons = document.createElement('div');
    buttons.style.cssText = 'display:flex;gap:8px;justify-content:flex-end;';
    
    const rejectBtn = document.createElement('button');
    rejectBtn.textContent = 'Reject';
    rejectBtn.style.cssText = 'padding:6px 16px;background:#f85149;color:#fff;border:none;border-radius:4px;cursor:pointer;font-weight:bold;';
    rejectBtn.onclick = () => {
      widget.remove();
      resolve(false);
    };
    
    const acceptBtn = document.createElement('button');
    acceptBtn.textContent = 'Accept';
    acceptBtn.style.cssText = 'padding:6px 16px;background:#2ea043;color:#fff;border:none;border-radius:4px;cursor:pointer;font-weight:bold;';
    acceptBtn.onclick = () => {
      widget.remove();
      resolve(true);
    };
    
    buttons.append(rejectBtn, acceptBtn);
    widget.append(header, diffView, buttons);
    
    // Append to the current turn
    const turn = document.querySelector('.turn:last-child') || document.body;
    turn.appendChild(widget);
    widget.scrollIntoView({ behavior: 'smooth', block: 'center' });
  });
}

export async function execTool(name, args) {
  switch (name) {

    case 'suggest_mode':
      return { success: true, _ui: 'suggest_mode', mode: args.mode, reason: args.reason,
        message: `Suggested: ${args.mode} — ${args.reason}` };

    case 'init_filesystem': {
      if (args.type === 'machine') {
        const n = await machOpen();
        if (n) { Bus.emit('fs:init', { type: 'machine', name: n }); return { success: true, message: 'Opened folder: ' + n }; }
        return { success: false, message: 'User cancelled folder picker.' };
      }
      const sn = await initIDBSession({ name: args.name, firstPrompt: args.firstPrompt });
      return { success: true, message: 'IDB session ready: ' + sn, session: sn };
    }

    case 'switch_workspace': {
      const sn = await switchWorkspace(args.name);
      return { success: true, message: 'Switched to session: ' + sn, session: sn };
    }

    case 'list_workspaces': {
      const list = await refreshSessions();
      const text = list.length
        ? list.map(s => `${s.active ? '→' : ' '} ${s.name}  (${s.size} files)  — ${s.displayName}${s.firstPrompt ? ' :: ' + s.firstPrompt.slice(0, 50) : ''}`).join('\n')
        : '(no sessions yet)';
      return { success: true, sessions: list, message: text };
    }

    case 'delete_workspace':
      await deleteSession(args.name);
      return { success: true, message: 'Deleted session: ' + args.name };

    case 'save_to_memory': {
      const i = S.memory.findIndex(m => m.key === args.key);
      const entry = { key: args.key, val: args.value, ts: Date.now() };
      if (i >= 0) S.memory[i] = entry; else S.memory.push(entry);
      saveState();
      Bus.emit('memory:update', S.memory);
      return { success: true, message: `Memory saved: "${args.key}"` };
    }

    case 'list_directory': {
      const items = await fsList(args.path);
      const text = items.map(i => (i.type === 'dir' ? '[DIR] ' : '[FILE] ') + i.name).join('\n');
      return { success: true, items, message: text || '(empty)' };
    }

    case 'read_file': {
      const content = await fsRead(args.path);
      return { success: true, content, path: args.path, lines: content.split('\n').length };
    }

    case 'read_file_range': {
      const r = await fsReadRange(args.path, args.offset || 0, args.limit || 100);
      return {
        success: true, content: r.content, path: args.path,
        offset: r.offset, total: r.total,
        message: `Lines ${r.offset + 1}-${Math.min(r.offset + r.limit, r.total)} of ${r.total}`,
      };
    }

    case 'read_many_files': {
      const results = {}, errors = {};
      for (const p of args.paths) {
        try { results[p] = await fsRead(p); } catch (e) { errors[p] = e.message; }
      }
      return { success: true, results, errors };
    }

    case 'write_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: writes not allowed.' };
      let before = '';
      try { before = await fsRead(args.path); } catch {}
      const diff = diffLines(before, args.content);
      const isNew = !before;
      
      // In edit mode, wait for user approval before applying
      if (S.mode === 'edit') {
        const approved = await waitForApproval(args.path, diff, isNew);
        if (!approved) {
          return { success: false, message: `User rejected changes to ${args.path}` };
        }
      }
      
      await fsWrite(args.path, args.content);
      Bus.emit('fs:changed', { path: args.path });
      recordPendingDiff({ path: args.path, before, after: args.content, diff, isNew });
      recordEdit(args.path, before, args.content, 'write_file', args);
      return { success: true, path: args.path, diff, isNew, _ui: 'diff',
        message: (before ? 'Wrote ' : 'Created ') + args.path + ` (+${diff.stats.add}, -${diff.stats.del})` };
    }

    case 'edit_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: edits not allowed.' };
      let content = '', isNew = false;
      try { content = await fsRead(args.path); }
      catch (e) {
        if (args.create_if_missing) { content = ''; isNew = true; } else throw e;
      }
      let next = isNew ? (args.full_content || '') : content;
      const failed = [];
      if (!isNew && args.changes) {
        for (const c of args.changes) {
          if (next.includes(c.old)) next = next.replace(c.old, c.new);
          else failed.push('"' + c.old.slice(0, 40) + (c.old.length > 40 ? '...' : '') + '"');
        }
      } else if (args.full_content !== undefined) {
        next = args.full_content;
      }
      if (failed.length) return { success: false, message: `Could not find ${failed.length} change(s). Read the file again: ${failed.join(', ')}` };
      
      const diff = diffLines(isNew ? '' : content, next);
      
      // In edit mode, wait for user approval before applying
      if (S.mode === 'edit') {
        const approved = await waitForApproval(args.path, diff, isNew);
        if (!approved) {
          return { success: false, message: `User rejected changes to ${args.path}` };
        }
      }
      
      await fsWrite(args.path, next);
      Bus.emit('fs:changed', { path: args.path });
      recordPendingDiff({ path: args.path, before: content, after: next, diff, isNew });
      recordEdit(args.path, content, next, 'edit_file', args);
      return { success: true, path: args.path, diff, isNew, _ui: 'diff',
        message: (isNew ? 'Created ' : 'Edited ') + args.path + ` (+${diff.stats.add}, -${diff.stats.del})` };
    }

    case 'delete_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: deletes not allowed.' };
      await fsDelete(args.path);
      Bus.emit('fs:changed', { path: args.path });
      return { success: true, message: 'Deleted: ' + args.path };
    }

    case 'rename_file': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: renames not allowed.' };
      await fsRename(args.old_path, args.new_path);
      Bus.emit('fs:changed', { path: args.new_path });
      return { success: true, message: `Renamed: ${args.old_path} → ${args.new_path}` };
    }

    case 'make_directory': {
      if (S.mode === 'plan') return { success: false, message: 'PLAN mode: mkdir not allowed.' };
      await fsMkdir(args.path);
      Bus.emit('fs:changed', { path: args.path });
      return { success: true, message: 'Created directory: ' + args.path };
    }

    case 'git_status': {
      if (S.fsMode !== 'machine') return { success: false, message: 'Git only in machine mode.' };
      const { machGit } = await import('./fs.js');
      const br = await machGit();
      S.gitBranch = br;
      Bus.emit('status:update', {});
      return { success: true, branch: br, message: br ? 'Branch: ' + br : 'Not a git repo.' };
    }

    case 'fetch_request': {
      try {
        const opts = { method: args.method || 'GET', headers: args.headers || {} };
        if (args.body) opts.body = args.body;
        const r = await fetch(args.url, opts);
        const text = (await r.text()).slice(0, 8000);
        return { success: true, status: r.status, body: text, _ui: 'fetch' };
      } catch (e) { return { success: false, message: 'Fetch error: ' + e.message }; }
    }

    case 'add_todo': {
      S.todos.push({ text: args.text, list: args.list || 'main', done: false, id: uid(), ts: Date.now() });
      saveState();
      Bus.emit('todos:update', S.todos);
      return { success: true, message: 'TODO added: "' + args.text + '"' };
    }

    case 'complete_todo': {
      const list = args.list || 'main';
      const filtered = S.todos.filter(t => t.list === list);
      if (args.index >= 0 && args.index < filtered.length) {
        filtered[args.index].done = true;
        saveState();
        Bus.emit('todos:update', S.todos);
        return { success: true, message: 'Completed: "' + filtered[args.index].text + '"' };
      }
      return { success: false, message: 'Index ' + args.index + ' not found' };
    }

    case 'list_todos': {
      const t = args.list ? S.todos.filter(x => x.list === args.list) : S.todos;
      return { success: true, todos: t,
        message: t.length ? t.map((x, i) => (x.done ? '✓' : '○') + ` [${i}] ${x.text}`).join('\n') : 'No todos' };
    }

    case 'display_markdown':
      return { success: true, _ui: 'markdown', content: args.content, title: args.title };

    case 'run_javascript': {
      const logs = [];
      const orig = console.log;
      console.log = (...a) => logs.push(a.map(x =>
        typeof x === 'object' ? JSON.stringify(x, null, 2) : String(x)).join(' '));
      let out = '', err = '';
      try {
        const v = eval(args.code);
        if (v !== undefined) logs.push(String(v));
      } catch (e) { err = e.message; }
      finally { console.log = orig; }
      out = logs.join('\n');
      return { success: !err, output: out, error: err, _ui: 'js',
        message: err ? 'Error: ' + err : (out || '(no output)') };
    }

    case 'display_html':
      return { success: true, _ui: 'html', html: args.html, title: args.title, height: args.height || 300 };

    case 'create_artifact': {
      const art = await createArtifact(args);
      return { success: true, _ui: 'artifact', artifact: art,
        message: `Artifact created: ${args.title} (${args.type})` };
    }

    case 'spawn_subagent': {
      const result = await spawnSubagent(args.task, args.system_prompt);
      return { success: true, summary: result.summary, _ui: 'subagent',
        message: 'Subagent completed: ' + result.summary.slice(0, 200) };
    }

    case 'search_conversations': {
      const q = args.query.toLowerCase();
      const r = S.convs.filter(c => (c.title + JSON.stringify(c.msgs)).toLowerCase().includes(q)).slice(0, 5);
      return { success: true, results: r,
        message: r.length ? r.map(c => `"${c.title}"`).join(', ') : 'No matches.' };
    }

    case 'date_now': {
      const n = new Date();
      return { success: true, iso: n.toISOString(), local: n.toLocaleString(),
        message: n.toLocaleString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }) };
    }

    case 'make_pdf': {
      const w = window.open('', '_blank');
      w.document.write(`<!DOCTYPE html><html><head><title>${args.filename || 'doc'}</title>
<style>body{font-family:Georgia,serif;max-width:780px;margin:48px auto;padding:20px;font-size:14px;line-height:1.7;}
h1,h2,h3{font-family:sans-serif;}code{background:#f4f4f4;padding:2px 5px;border-radius:3px;font-size:12px;}
pre{background:#f4f4f4;padding:10px;border-radius:5px;overflow:auto;}</style>
</head><body><pre id=c></pre><script>
const raw=document.getElementById('c');
raw.style.whiteSpace='pre-wrap';raw.style.fontFamily='Georgia,serif';raw.style.background='none';raw.style.padding='0';
raw.textContent=${JSON.stringify(args.content)};window.print();<\/script></body></html>`);
      w.document.close();
      return { success: true, message: 'PDF print dialog opened for: ' + (args.filename || 'document') };
    }

    case 'clarify': {
      return new Promise(resolve => {
        const w = makeClarifyWidget(args.question, ans => resolve({ success: true, answer: ans }));
        Bus.emit('widget:append', w);
        if (S.mode === 'yolo') {
          setTimeout(() => {
            const def = args.default_answer || 'Continue with best default.';
            const input = w.querySelector('.clr-inp');
            if (input) { input.value = def; input.disabled = true; }
            resolve({ success: true, answer: def, auto: true });
          }, 30000);
        }
      });
    }

    case 'simple_question': {
      return new Promise(resolve => {
        const w = makeSQWidget(args.question, args.options, ans => resolve({ success: true, answer: ans }));
        Bus.emit('widget:append', w);
        if (S.mode === 'yolo') {
          setTimeout(() => resolve({ success: true, answer: args.options[args.default_index || 0], auto: true }), 30000);
        }
      });
    }

    case 'think_deeper': {
      const r = await apiChat([{
        role: 'user',
        content: `Think deeply about this problem and provide thorough analysis:\n\n**Problem:** ${args.problem}${args.context ? '\n\n**Context:** ' + args.context : ''}\n\nProvide clear analysis and concrete next steps.`
      }]);
      const analysis = r.choices?.[0]?.message?.content || 'No analysis generated';
      return { success: true, analysis, _ui: 'think_deeper' };
    }

    default:
      return { success: false, message: 'Unknown tool: ' + name };
  }
}
